### ISSUE TITLE
Cannot use striking force sortie

### ISSUE THREAD

**Issue by n0k0m3** [perryhuynh/kcauto#100]
## Log for crash that occurred at 2018-03-09 16.06.58

You may submit this as an issue to the KCAuto-Kai Github Repository at: 
> https://github.com/mrmin123/kcauto-kai/issues

Or if you think it has something to do with KAGA then you may submit the issue at:
> https://github.com/waicool20/KAGA/issues

You may want to use a service like [http://pastebin.com/] and replace the sections Configuration and Console Log with a paste link.

-------------------------------------------

#### Issue / Additional Information

<Fill this in with whatever you think may help debug the problem like the game state when the crash occurred etc.>

#### Environment details

* KCAuto-Kai Version: 0.3.3
* Viewer/browser: Chrome
* Operating system: Windows 10 10.0 amd64

-------------------------------------------
#### Configuration

```
[General]
Program = Chrome
JSTOffset = -14

[ScheduledSleep]
Enabled = false
StartTime = 0000
SleepLength = 1.97

[Expeditions]
Enabled = true
Fleet2 = 2
Fleet3 = 
Fleet4 = 37

[PvP]
Enabled = false

[Combat]
Enabled = true
Engine = legacy
Map = E-5
CombatNodes = 5
FleetMode = striking
NodeSelects = 
Formations = 1:diamond, 2:diamond, 3:double_line, 4:double_line, 5:line_ahead
NightBattles = 1:False, 2:False, 3:False, 4:False, 5:True
RetreatLimit = heavy
RepairLimit = moderate
RepairTimeLimit = 0000
LBASGroups = 1, 2
LBASGroup1Nodes = D, F
LBASGroup2Nodes = L, L
LBASGroup3Nodes = 
MiscOptions = CheckFatigue, ClearStop

[ShipSwitcher]
Enabled = false
Slot1Criteria = fatigue
Slot1Ships = 
Slot2Criteria = 
Slot2Ships = 
Slot3Criteria = 
Slot3Ships = 
Slot4Criteria = 
Slot4Ships = 
Slot5Criteria = 
Slot5Ships = 
Slot6Criteria = 
Slot6Ships = 

[Quests]
Enabled = false


```
-------------------------------------------
#### Console log
Got Regex search? Use this to find tracebacks easily!
> (([error] --- Traceback --- error source first)(.*\n)+?([error] --- Traceback --- end --------------))

```
[KAGA] [2018-03-09 15:48:52] [c.w.k.k.KancolleAutoKai] INFO - Starting new KCAuto-Kai session (Version: 0.3.3)
[KAGA] [2018-03-09 15:48:52] [c.w.k.k.KancolleAutoKai] DEBUG - Launching with command: java -jar D:\SikuliX\sikulix.jar -r D:\kcauto-kai-master\kcauto-kai.sikuli -- cfg D:\KAGA 2\kaga\E-5 TP-config.ini
[KAGA] [2018-03-09 15:48:53] [c.w.k.k.KancolleAutoKai] DEBUG - Session profile: {"name":"E-5 TP","general":{"jstOffset":-14,"program":"Chrome"},"scheduledSleep":{"enabled":false,"startTime":"0000","length":1.97},"expeditions":{"enabled":true,"fleet2":["2"],"fleet3":[],"fleet4":["37"]},"pvp":{"enabled":false},"sortie":{"enabled":true,"engine":"LEGACY","map":"E-5","nodes":5,"fleetMode":"STRIKING","nodeSelects":[],"formations":["1:diamond","2:diamond","3:double_line","4:double_line","5:line_ahead"],"nightBattles":["1:False","2:False","3:False","4:False","5:True"],"retreatLimit":"CRITICAL","repairLimit":"MODERATE","repairTimeLimit":"0000","lbasGroups":["1","2"],"lbasGroup1Nodes":["D","F"],"lbasGroup2Nodes":["L","L"],"lbasGroup3Nodes":[],"miscOptions":["CHECK_FATIGUE","CLEAR_STOP"]},"shipSwitcher":{"enabled":false,"slot1Criteria":["FATIGUE"],"slot1Ships":[],"slot2Criteria":[],"slot2Ships":[],"slot3Criteria":[],"slot3Ships":[],"slot4Criteria":[],"slot4Ships":[],"slot5Criteria":[],"slot5Ships":[],"slot6Criteria":[],"slot6Ships":[]},"quests":{"enabled":false}}
[KAGA] [2018-03-09 15:48:53] [c.w.k.k.YuuBot] INFO - Reporting stats to YuuBot!
[KAGA] [2018-03-09 15:48:54] [c.w.k.k.YuuBot] DEBUG - Stats reported to YuuBot! Response was: 200
[KAGA] [2018-03-09 15:48:54] [c.w.k.k.YuuBot] DEBUG - Stats reported to YuuBot! Response was: 200
[KAGA] [2018-03-09 15:48:54] [c.w.k.k.YuuBot] DEBUG - Stats reported to YuuBot! Response was: 200
[KAGA] [2018-03-09 15:48:55] [c.w.k.k.YuuBot] DEBUG - Crash reported to YuuBot! Response was: 200
[KAGA] [2018-03-09 15:49:12] [c.w.k.k.KancolleAutoKai] INFO - Terminating current KCAuto-Kai session
[KAGA] [2018-03-09 15:49:13] [c.w.k.k.KancolleAutoKai] INFO - KCAuto-Kai session has terminated!
[KAGA] [2018-03-09 15:49:13] [c.w.k.k.KancolleAutoKai] DEBUG - Exit Value was 1
[KAGA] [2018-03-09 15:49:13] [c.w.k.k.YuuBot] INFO - Reporting stats to YuuBot!
[KAGA] [2018-03-09 15:49:13] [c.w.k.k.KancolleAutoKai] INFO - User initiated termination, exiting kancolle-auto process loop regardless...
[KAGA] [2018-03-09 15:49:13] [c.w.k.k.YuuBot] DEBUG - Stats reported to YuuBot! Response was: 200
[KAGA] [2018-03-09 16:04:45] [c.w.k.c.KancolleAutoProfile] INFO - Saving KancolleAuto profile
[KAGA] [2018-03-09 16:04:45] [c.w.k.c.KancolleAutoProfile] DEBUG - Saving to D:\KAGA 2\kaga\E-5 TP-config.ini
[KAGA] [2018-03-09 16:04:46] [c.w.k.c.KancolleAutoProfile] INFO - Saving KancolleAuto profile was successful
[KAGA] [2018-03-09 16:04:46] [c.w.k.c.KancolleAutoProfile] DEBUG - Saved {"name":"E-5 TP","general":{"jstOffset":-14,"program":"Chrome"},"scheduledSleep":{"enabled":false,"startTime":"0000","length":1.97},"expeditions":{"enabled":true,"fleet2":["2"],"fleet3":[],"fleet4":["37"]},"pvp":{"enabled":false},"sortie":{"enabled":true,"engine":"LEGACY","map":"E-5","nodes":5,"fleetMode":"STRIKING","nodeSelects":[],"formations":["1:diamond","2:diamond","3:double_line","4:double_line","5:line_ahead"],"nightBattles":["1:False","2:False","3:False","4:False","5:True"],"retreatLimit":"CRITICAL","repairLimit":"MODERATE","repairTimeLimit":"0000","lbasGroups":["1","2"],"lbasGroup1Nodes":["D","F"],"lbasGroup2Nodes":["L","L"],"lbasGroup3Nodes":[],"miscOptions":["CHECK_FATIGUE","CLEAR_STOP"]},"shipSwitcher":{"enabled":false,"slot1Criteria":["FATIGUE"],"slot1Ships":[],"slot2Criteria":[],"slot2Ships":[],"slot3Criteria":[],"slot3Ships":[],"slot4Criteria":[],"slot4Ships":[],"slot5Criteria":[],"slot5Ships":[],"slot6Criteria":[],"slot6Ships":[]},"quests":{"enabled":false}} to D:\KAGA 2\kaga\E-5 TP-config.ini
[KAGA] [2018-03-09 16:04:46] [c.w.k.k.KancolleAutoKai] INFO - Starting new KCAuto-Kai session (Version: 0.3.3)
[KAGA] [2018-03-09 16:04:46] [c.w.k.k.KancolleAutoKai] DEBUG - Launching with command: java -jar D:\SikuliX\sikulix.jar -r D:\kcauto-kai-master\kcauto-kai.sikuli -- cfg D:\KAGA 2\kaga\E-5 TP-config.ini
[KAGA] [2018-03-09 16:04:46] [c.w.k.k.KancolleAutoKai] DEBUG - Session profile: {"name":"E-5 TP","general":{"jstOffset":-14,"program":"Chrome"},"scheduledSleep":{"enabled":false,"startTime":"0000","length":1.97},"expeditions":{"enabled":true,"fleet2":["2"],"fleet3":[],"fleet4":["37"]},"pvp":{"enabled":false},"sortie":{"enabled":true,"engine":"LEGACY","map":"E-5","nodes":5,"fleetMode":"STRIKING","nodeSelects":[],"formations":["1:diamond","2:diamond","3:double_line","4:double_line","5:line_ahead"],"nightBattles":["1:False","2:False","3:False","4:False","5:True"],"retreatLimit":"CRITICAL","repairLimit":"MODERATE","repairTimeLimit":"0000","lbasGroups":["1","2"],"lbasGroup1Nodes":["D","F"],"lbasGroup2Nodes":["L","L"],"lbasGroup3Nodes":[],"miscOptions":["CHECK_FATIGUE","CLEAR_STOP"]},"shipSwitcher":{"enabled":false,"slot1Criteria":["FATIGUE"],"slot1Ships":[],"slot2Criteria":[],"slot2Ships":[],"slot3Criteria":[],"slot3Ships":[],"slot4Criteria":[],"slot4Ships":[],"slot5Criteria":[],"slot5Ships":[],"slot6Criteria":[],"slot6Ships":[]},"quests":{"enabled":false}}
[KAGA] [2018-03-09 16:04:46] [c.w.k.k.YuuBot] INFO - Reporting stats to YuuBot!
[KAGA] [2018-03-09 16:04:47] [c.w.k.k.YuuBot] DEBUG - Stats reported to YuuBot! Response was: 200
[2018-03-09 16:05:13] Initializing config module
[2018-03-09 16:05:13] Reading config
[2018-03-09 16:05:13] Validating config
[2018-03-09 16:05:13] Starting kancolle-auto!
[log] App.focus:  [5752:Chrome]
[2018-03-09 16:05:16] At home
[2018-03-09 16:05:19] At home
[2018-03-09 16:05:19] Refreshing home.
[log] CLICK on L(134,436)@S(0)[0,0 1366x768] (533 msec)
[log] CLICK on L(75,333)@S(0)[0,0 1366x768] (522 msec)
[log] App.focus:  [5752:Chrome]
[2018-03-09 16:05:27] At home
[2018-03-09 16:05:28] At home
[2018-03-09 16:05:30] At home
[2018-03-09 16:05:30] Navigating to expedition screen.
[log] CLICK on L(217,355)@S(0)[0,0 1366x768] (522 msec)
[log] CLICK on L(684,308)@S(0)[0,0 1366x768] (521 msec)
[2018-03-09 16:05:35] Sortieing fleet 2 to expedition 2
[log] CLICK on L(318,285)@S(0)[0,0 1366x768] (521 msec)
[log] CLICK on L(687,530)@S(0)[0,0 1366x768] (522 msec)
[2018-03-09 16:05:41] Fleet needs resupply!
[log] CLICK on L(134,522)@S(0)[0,0 1366x768] (522 msec)
[2018-03-09 16:05:43] Sortieing fleet 4 to expedition 37
[log] CLICK on L(358,518)@S(0)[0,0 1366x768] (521 msec)
[log] CLICK on L(288,381)@S(0)[0,0 1366x768] (521 msec)
[2018-03-09 16:05:51] Got valid timer (02:14:42)!
[2018-03-09 16:05:51] Expedition is already running. Return time: 2018-03-09 18:18:51
[2018-03-09 16:05:53] At side menu
[log] CLICK on L(21,288)@S(0)[0,0 1366x768] (534 msec)
[2018-03-09 16:05:55] Begin resupplying fleets.
[2018-03-09 16:05:55] Resupplying fleet 2.
[log] CLICK on L(177,208)@S(0)[0,0 1366x768] (521 msec)
[log] CLICK on L(116,209)@S(0)[0,0 1366x768] (521 msec)
[2018-03-09 16:05:59] Done resupplying fleets.
[2018-03-09 16:06:01] At side menu
[2018-03-09 16:06:01] Going home.
[log] CLICK on L(72,341)@S(0)[0,0 1366x768] (521 msec)
[log] App.focus:  [5752:Chrome]
[2018-03-09 16:06:06] At home
[2018-03-09 16:06:07] At home
[2018-03-09 16:06:09] At home
[2018-03-09 16:06:09] Navigating to combat screen.
[log] CLICK on L(194,325)@S(0)[0,0 1366x768] (520 msec)
[log] CLICK on L(197,318)@S(0)[0,0 1366x768] (522 msec)
[log] CLICK on L(718,534)@S(0)[0,0 1366x768] (521 msec)
[2018-03-09 16:06:16] Begin resupplying LBAS groups.
[log] CLICK on L(264,475)@S(0)[0,0 1366x768] (522 msec)
[2018-03-09 16:06:19] Resupplying LBAS group 1.
[log] CLICK on L(780,299)@S(0)[0,0 1366x768] (523 msec)
[2018-03-09 16:06:23] LBAS Group 1 fatigue state: Rested
[2018-03-09 16:06:23] LBAS group switched to sortie mode.
[2018-03-09 16:06:25] Resupplying LBAS group 2.
[log] CLICK on L(686,207)@S(0)[0,0 1366x768] (521 msec)
[log] CLICK on L(776,297)@S(0)[0,0 1366x768] (521 msec)
[2018-03-09 16:06:30] LBAS Group 2 fatigue state: Rested
[2018-03-09 16:06:30] LBAS group switched to sortie mode.
[log] CLICK on L(193,484)@S(0)[0,0 1366x768] (531 msec)
[log] CLICK on L(721,364)@S(0)[0,0 1366x768] (523 msec)
[log] CLICK on L(661,304)@S(0)[0,0 1366x768] (532 msec)
[log] CLICK on L(653,527)@S(0)[0,0 1366x768] (528 msec)
[log] CLICK on L(417,199)@S(0)[0,0 1366x768] (522 msec)
[2018-03-09 16:06:53] Fleet needs resupply!
[error] script [ D:\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\kcauto-kai.py", line 65, in <module>
    kcauto_kai.run_combat_cycle()
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\kcauto-kai.py", line 65, in <module>
    kcauto_kai.run_combat_cycle()
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\main.py", line 325, in run_combat_cycle
    if self.modules['combat'].combat_logic_wrapper():
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 110, in combat_logic_wrapper
    if self._conduct_pre_sortie_checks():
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 229, in _conduct_pre_sortie_checks
    needs_resupply, self.dmg, fleet_fatigue = (
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 306, in _run_pre_sortie_fleet_check_logic
    if self.config.combat['fleet_mode'] == 'striking'
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 1074, in check_damages_7th
    Util.click_preset_region(regions, '7th_next')
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\util.sikuli\util.py", line 382, in click_preset_region
    cls.rejigger_mouse(regions, preset)
  File "D:\kcauto-kai-master\kcauto-kai.sikuli\util.sikuli\util.py", line 361, in rejigger_mouse
    rand_x = regions['game'].x + cls.randint_gauss(x1, x2)
KeyError: 'game'

[KAGA] [2018-03-09 16:06:58] [c.w.k.k.KancolleAutoKai] INFO - KCAuto-Kai session has terminated!
[KAGA] [2018-03-09 16:06:58] [c.w.k.k.KancolleAutoKai] DEBUG - Exit Value was 1
[KAGA] [2018-03-09 16:06:58] [c.w.k.k.YuuBot] INFO - Reporting stats to YuuBot!
[KAGA] [2018-03-09 16:06:58] [c.w.k.k.KancolleAutoKai] INFO - KCAuto-Kai didn't terminate gracefully
[KAGA] [2018-03-09 16:06:58] [c.w.k.k.YuuBot] INFO - Reporting stats to YuuBot!

```

Cannot figure where the error is since `rand_x = regions['game'].x + cls.randint_gauss(x1, x2)` is used globally and didn't cause any problem except this.

What I tried:
- Put Util.kc_sleep(2) between 1072 and 1073 in combat.py, still the same thing.
- Changed coord of `7th_next` in util.py: `'7th_next': (384, 413, 484, 515)`, still give the same error (btw @mrmin123 please update `7th_next` coord in your next commit

Gonna try without kaga but pretty sure it's gonna be the same...
Plz help

**Comment by mrmin123** [comment]
Please see #97. Fix is in `staging` branch already.
