### ISSUE TITLE
Completely fails to start

### ISSUE THREAD

**Issue by SpawnageLoong** [perryhuynh/kcauto#130]
#### Environment details

* KCAuto-Kai version 0.4.4
* Chrome/KC3改
* Windows 10 (x64)

#### Issue

KCAuto-Kai completely fails to start. It only gets as far as bringing the Chrome window forwards before the error comes up and the program stops.

#### Log
```
[94m[2018-03-23 00:33:51] Initializing config module[0m
[94m[2018-03-23 00:33:51] Reading config[0m
[94m[2018-03-23 00:33:51] Validating config[0m
[94m[2018-03-23 00:33:51] Starting kancolle-auto![0m
[log] App.focus:  [8268:Chrome]
[log] App.focus:  [8268:Chrome]
[error] script [ C:\Users\loong\Downloads\Random-Stuff\kcauto-kai-master\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\Users\loong\Downloads\Random-Stuff\kcauto-kai-master\kcauto-kai-master\kcauto-kai.sikuli\kcauto-kai.py", line 82, in <module>
    Recovery.recover(kcauto_kai, config, e)
  File "C:\Users\loong\Downloads\Random-Stuff\kcauto-kai-master\kcauto-kai-master\kcauto-kai.sikuli\recovery.py", line 24, in recover
    kcauto_kai.kc_region if kcauto_kai.kc_region
  File "C:\Users\loong\Downloads\Random-Stuff\kcauto-kai-master\kcauto-kai-master\kcauto-kai.sikuli\util.sikuli\util.py", line 285, in focus_kc
    reference_region = kc.wait(Pattern('kc_reference_point.png').exact())
  Line 2782, in file Region.java

        at org.sikuli.script.Region.wait(Region.java:2782)
        at org.sikuli.script.Region.wait(Region.java:2729)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
org.sikuli.script.FindFailed: FindFailed: kc_reference_point.png: (12x12) in R[0,0 2736x1256]@S(0) E:Y, T:1.0
  Line 2782, in file Region.java
```

#### Config

Nothing should be happening other than sending fleet 4 for expedition 2. 

```
# config automatically generated from kcauto-kai frontend (v0.4.4)

[General]
Program: Chrome
JSTOffset: -1
Pause: False

[ScheduledSleep]
SleepEnabled: False
SleepStartTime: 0000
SleepLength: 4
ExpeditionSleepEnabled: False
ExpeditionSleepStartTime: 0000
ExpeditionSleepLength: 3
CombatSleepEnabled: False
CombatSleepStartTime: 0000
CombatSleepLength: 5

[Expeditions]
Enabled: True
Fleet2: 
Fleet3: 
Fleet4: 2

[PvP]
Enabled: False

[Combat]
Enabled: False
Engine: live
Map: 1-1
FleetMode: 
CombatNodes: 
NodeSelects: 
Formations: 
NightBattles: 
RetreatLimit: heavy
RepairLimit: moderate
RepairTimeLimit: 0030
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: 

[ShipSwitcher]
Enabled: False
Slot1Criteria: 
Slot1Ships: 
Slot2Criteria: 
Slot2Ships: 
Slot3Criteria: 
Slot3Ships: 
Slot4Criteria: 
Slot4Ships: 
Slot5Criteria: 
Slot5Ships: 
Slot6Criteria: 
Slot6Ships: 

[Quests]
Enabled: True

```

**Comment by perryhuynh** [comment]
is it scaled correctly to 100%?

**Comment by mrmin123** [comment]
See also the [FAQ](https://github.com/mrmin123/kcauto-kai/wiki/FAQ#kcauto-kai-starts-but-it-immediately-errors-out-attributeerror-nonetype-object-has-no-attribute-mousemove-or-findfailed-error-looking-for-kc_reference_pointpng), third entry under 'Usage Questions'.

**Comment by SpawnageLoong** [comment]
Yes, my Chrome window is scaled at 100%. The log I copied is the entire log from right after I started it, and I can't find the attribute error, or any if the errors covered in the FAQ.

**Comment by mrmin123** [comment]
You're starting the script with the game at the home port? Could you provide a screenshot of the game screen? Feel free to censor out your in-game name.

**Comment by perryhuynh** [comment]
Possibly windows scaling?

![](https://i.imgur.com/idIKtee.png)

**Comment by mrmin123** [comment]
Closing due to inactivity.
