### ISSUE TITLE
Random Crashes in Fleet Selection step 

### ISSUE THREAD

**Issue by cmonbruh123** [perryhuynh/kcauto#182]
#### Environment details

* kcauto-kai version (version on first line of CHANGELOG.md): 0.5.0
* Viewer/browser: Chrome 
* Operating system: 64 bit Windows 10

#### Issue variability

Script crashes randomly (ie.  sometimes it runs for up to 6 hours, sometimes up to just 2). 

#### Issue

Seems to always crash in the formation selection screen. Cannot reproduce the timing but the script seems to crash only on the combat selection screen. 

#### Log
```
[94m[2018-06-08 04:43:23] Fleet 1 damage counts: 0 heavy / 0 moderate / 4 minor / 0 under repair[0m
[94m[2018-06-08 04:43:24] Fleet 1 fatigue state: Rested[0m
[log] CLICK on L(762,524)@S(0)[0,0 2560x1440] (524 msec)
[94m[2018-06-08 04:43:25] Beginning combat sortie.[0m
[94m[2018-06-08 04:43:36] Fleet at Node None[0m
[error] script [ C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli\kcauto-kai.py", line 66, in <module>
    kcauto_kai.run_combat_cycle()
  File "C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli\kcauto-kai.py", line 66, in <module>
    kcauto_kai.run_combat_cycle()
  File "C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli\main.py", line 325, in run_combat_cycle
    if self.modules['combat'].combat_logic_wrapper():
  File "C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 138, in combat_logic_wrapper
    self._run_combat_logic()
  File "C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 351, in _run_combat_logic
    at_node, dialogue_click = self._run_loop_between_nodes()
  File "C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 540, in _run_loop_between_nodes
    formations = self._resolve_formation()
  File "C:\Kancolle\kcauto-kai-master\kcauto-kai.sikuli\combat.sikuli\combat.py", line 743, in _resolve_formation
    Util.log_msg(
AttributeError: 'NoneType' object has no attribute 'name'
```

#### Config
```
[insert relevant config sections here]
```

**Comment by mrmin123** [comment]
Please update to 0.5.1.

**Comment by cmonbruh123** [comment]
That fixed the problem!
