### ISSUE TITLE
FleetSwitcher bug between cycles

### ISSUE THREAD

**Issue by Evolto2019** [perryhuynh/kcauto#195]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`):2.0.0
* Viewer/browser:Chrome
* Operating system and/or VM:Windows 10

#### Issue variability
consistent
#### Issue

When the first cycle which uses the fleet preset 1 ends,kcauto will stop rather than starting a new cycle uses the preset 6.It really confuses me.

#### Log
```
[94m[2018-07-08 13:21:31] At home[0m
[debug] Image: reused: expedition_flag.png (file:/C:/kcauto-master/kcauto.sikuli/expedition.sikuli/expedition_flag.png)
[debug] Region: exists: waiting 1.0 secs for expedition_flag.png to appear in R[583,65 60x60]@S(0)
[debug] Region: exists: expedition_flag.png did not appear [1014 msec]
[error] script [ C:\kcauto-master\kcauto.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\kcauto-master\kcauto.sikuli\kcauto.py", line 66, in <module>
    kcauto.run_combat_cycle()
  File "C:\kcauto-master\kcauto.sikuli\kcauto.py", line 66, in <module>
    kcauto.run_combat_cycle()
  File "C:\kcauto-master\kcauto.sikuli\main.py", line 344, in run_combat_cycle
    if self.modules['fleet_switcher'].switch_combat_fleet():
  File "C:\kcauto-master\kcauto.sikuli\fleetswitcher.sikuli\fleetswitcher.py", line 59, in switch_combat_fleet
    if not self.last_combat_fleet or len(self.combat['fleets']) == 1:
AttributeError: 'FleetSwitcherModule' object has no attribute 'combat'
```

#### Config
```
[PvP]
Enabled: True
Fleet: 2

[Combat]
Enabled: True
Engine: legacy
Fleets: 1,6
Map: 1-5
FleetMode: 
RetreatNodes: 3
NodeSelects: 
Formations: 1:line_abreast,2:line_abreast,3:line_abreast
NightBattles: 
RetreatLimit: heavy
RepairLimit: heavy
RepairTimeLimit: 0100
LBASGroups: 
LBASGroup1Nodes: 
LBASGroup2Nodes: 
LBASGroup3Nodes: 
MiscOptions: CheckFatigue,ClearStop
```

**Comment by mrmin123** [comment]
Oops. I'll have a fix for this out tomorrow. In the meantime, you should be able to fix this by changing lines 59 and 67 of `fleetswitcher.py` to these, respectively:

```python
            if not self.last_combat_fleet or len(self.config.combat['fleets']) == 1:
```

```python
                    0 if temp_index == len(self.config.combat['fleets'])
```

**Comment by Evolto2019** [comment]
@mrmin123 Thx！
