### ISSUE TITLE
Chrome crash recovery

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#235]
![image](https://user-images.githubusercontent.com/4326866/45250399-30294280-b2e7-11e8-96e8-f7df57fedf27.png)

**Comment by perryhuynh** [comment]
This issue _might_ resolve itself after the current September 8th maintenance

**Comment by mrmin123** [comment]
@perryhuynh is that just conjecture or..?

**Comment by perryhuynh** [comment]
The event was delayed by a week due so they could fix issues with memory leaks etc brought on by the switch to HTML5 and I believe this issue only came about since that switch so there's a possibility that it might resolve itself after the maintenance

**Comment by mrmin123** [comment]
Good to know. Fingers crossed.

**Comment by stackhanovets** [comment]
They have not fixed this at all.

![nope](https://user-images.githubusercontent.com/16455270/45347447-ce056180-b5b4-11e8-9c96-961e00a21dc0.png)

**Comment by mrmin123** [comment]
@stackhanovets were you running kca when it crashed? If so, did it recover? I wasn't able to test the logic for this in in-game conditions.

**Comment by stackhanovets** [comment]
@mrmin123 There was no recovery done by `kcauto` during combat stage. The crash has been probably caused by combat-related animations.

```
[94m[2018-09-12 TIME] At home[0m
[94m[2018-09-12 TIME] At home[0m
[94m[2018-09-12 TIME] Navigating to fleetcomp screen.[0m
[log] CLICK on L(187,412)@S(0)[0,0 1920x1080] (528 msec)
[log] CLICK on L(97,309)@S(0)[0,0 1920x1080] (796 msec)
[log] CLICK on L(172,654)@S(0)[0,0 1920x1080] (762 msec)
[94m[2018-09-12 TIME] Switching to fleet preset 1.[0m
[log] CLICK on L(512,383)@S(0)[0,0 1920x1080] (524 msec)
[94m[2018-09-12 TIME] At side menu[0m
[94m[2018-09-12 TIME] Going home.[0m
[log] CLICK on L(175,462)@S(0)[0,0 1920x1080] (527 msec)
[94m[2018-09-12 TIME] At home[0m
[94m[2018-09-12 TIME] At home[0m
[94m[2018-09-12 TIME] Navigating to pvp screen.[0m
[log] CLICK on L(380,411)@S(0)[0,0 1920x1080] (527 msec)
[log] CLICK on L(740,430)@S(0)[0,0 1920x1080] (544 msec)
[log] CLICK on L(1121,689)@S(0)[0,0 1920x1080] (528 msec)
[94m[2018-09-12 TIME] PvPing against 1 ships (0 subs).[0m
[94m[2018-09-12 TIME] Selecting formation line ahead and True on night battle.[0m
[log] CLICK on L(389,693)@S(0)[0,0 1920x1080] (529 msec)
[log] CLICK on L(748,732)@S(0)[0,0 1920x1080] (541 msec)
[94m[2018-09-12 TIME] Beginning PvP sortie.[0m
[log] CLICK on L(777,355)@S(0)[0,0 1920x1080] (526 msec)

<EOF>
```

**Comment by stackhanovets** [comment]
Again, the log tail (no script crash):

```
[log] CLICK on L(807,365)@S(0)[0,0 1920x1080] (540 msec)
[2018-09-13 TIME] Custom night battle specified for node #3.
[2018-09-13 TIME] Commencing night battle.
[log] CLICK on L(838,449)@S(0)[0,0 1920x1080] (528 msec)
[2018-09-13 TIME] Fleet 1 damage counts: 1 heavy / 2 moderate / 2 minor
```

**Comment by stackhanovets** [comment]
Finally, the crash recovery was triggered:
```
[2018-09-14 TIME] FindFailed: sortie_menu_combat.png: (190x232) seen at (322, 317) with 1.00 in R[69,81 1200x720]@S(0) E:Y, T:1.0
  Line 2761, in file Region.java

[2018-09-14 TIME] ** FindFailed error occurred; attempting basic recovery. **
[log] App.focus:  [3792:Chrome]
[log]  TYPE "#ESC."
[log]  TYPE " "
[log]  TYPE "#F10."
[2018-09-14 TIME] ** Chrome crash detected. **
[log]  TYPE "#F5."
[error] script [ C:\Users\USERNAME\Documents\Tools\kcauto\kcauto.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\Users\USERNAME\Documents\Tools\kcauto\kcauto.sikuli\kcauto.py", line 84, in <module>
    Recovery.recover(kcauto, config, e)
  File "C:\Users\USERNAME\Documents\Tools\kcauto\kcauto.sikuli\recovery.py", line 69, in recover
    Util.wait_and_click(
  File "C:\Users\USERNAME\Documents\Tools\kcauto\kcauto.sikuli\util.sikuli\util.py", line 508, in wait_and_click
    region.wait(target, time)
  Line 2761, in file Region.java

        at org.sikuli.script.Region.wait(Region.java:2761)
        at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
org.sikuli.script.FindFailed: FindFailed: game_start.png: (445x95) in R[60,1 1860x810]@S(0) E:Y, T:1.0
  Line 2761, in file Region.java
```

However, then script had terminated. The game had not enough time to load. Will see.
