### ISSUE TITLE
Bug with ship switching 

### ISSUE THREAD

**Issue by quaicai12** [perryhuynh/kcauto#252]
I cant do ship switch for normal sorties.
Was using KAGA

error log from Kaga

[2018-09-13 03:27:00] Potential replacement ships found in page 1 positions 2, 4, 5, 6, 7, 8, 9, 10
[error] script [ C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\kcauto.py", line 70, in <module>
    kcauto.run_ship_switch_cycle()
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\kcauto.py", line 70, in <module>
    kcauto.run_ship_switch_cycle()
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\main.py", line 421, in run_ship_switch_cycle
    self.modules['ship_switcher'].ship_switch_logic()
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\shipswitcher.sikuli\shipswitcher.py", line 114, in ship_switch_logic
    if self._resolve_replacement_ship(slot_config):
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\shipswitcher.sikuli\shipswitcher.py", line 491, in _resolve_replacement_ship
    return self._resolve_replacement_ship_by_asset(slot_config)
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\shipswitcher.sikuli\shipswitcher.py", line 608, in _resolve_replacement_ship_by_asset
    if self._choose_and_check_availability_of_ship(
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\shipswitcher.sikuli\shipswitcher.py", line 471, in _choose_and_check_availability_of_ship
    self._choose_ship_by_position(position)
  File "C:\Users\yolo\Downloads\kcauto-6.3.0\kcauto-6.3.0\kcauto.sikuli\shipswitcher.sikuli\shipswitcher.py", line 294, in _choose_ship_by_position
    Util.click_coords(
AttributeError: type object 'Util' has no attribute 'random_coords'

**Comment by mrmin123** [comment]
Oops, those should be renamed to `Util.random_coord`. Replace the following lines in their respective files with these (they'll say `Util.random_coords` right now):

`nav.py` `L423` and `L424`:
```python
                Util.random_coord(x_start, x_stop),
                Util.random_coord(y_start, y_stop))
```

`shipswitcher.py` `L296` and `L297`:
```python
            Util.random_coord(x_start, x_stop),
            Util.random_coord(y_start, y_stop))
```

**Comment by quaicai12** [comment]
it worked again 
thanks for the help
