### ISSUE TITLE
Error that shows on every startsup and fail to run scripts

### ISSUE THREAD

**Issue by Melxzy** [perryhuynh/kcauto#307]
#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): 6.8.5
* Viewer/browser: Google Chrome
* Operating system and/or VM: Win 7

#### Issue variability
This issue is happening everytime when trying to run a script

#### Issue

Error pops-up on the spot when trying to run the script, got latest updated kcauto(6.8.5) and sikulix(1.1.4).

#### Log
```
[94m[2018-10-07 03:16:48] Initializing config module[0m
[94m[2018-10-07 03:16:48] Reading config[0m

[error] script [ kcauto ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last): File "C:\Users\R\Downloads\kcauto-kai-master\kcauto-master\kcauto.sikuli\kcauto.py", line 46, in <module> config = Config('config.ini') File "C:\Users\R\Downloads\kcauto-kai-master\kcauto-master\kcauto.sikuli\config.py", line 44, in __init__ self.read() File "C:\Users\R\Downloads\kcauto-kai-master\kcauto-master\kcauto.sikuli\config.py", line 58, in read self._read_general(config) File "C:\Users\R\Downloads\kcauto-kai-master\kcauto-master\kcauto.sikuli\config.py", line 356, in _read_general self.jst_offset = config.getint('General', 'JSTOffset') File "C:\Users\R\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\ConfigParser.py", line 359, in getint File "C:\Users\R\AppData\Roaming\Sikulix\Extensions\jython-standalone-2.7.1.jar\Lib\ConfigParser.py", line 356, in _get ValueError: invalid literal for int() with base 10: '1.5'
```

**Comment by mrmin123** [comment]
`JSTOffset` in your config has to be an integer.
