### ISSUE TITLE
Chome Driver bugs

### ISSUE THREAD

**Issue by mrmin123** [perryhuynh/kcauto#397]
* When starting kancolle, it seems to have issues with generating the JSON data?
* Navigation issues to Quest:
```
[2019-12-01 18:51:59] Navigating to quest screen.
Traceback (most recent call last):
  File "C:\Users\Saint\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "main", mod_spec)
  File "C:\Users\Saint\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kcauto__main__.py", line 19, in <module>
    kcauto_main()
  File "kcauto\kcauto_wrapper.py", line 30, in kcautomain
    .kcauto.run_quest_logic(home_after=True)
  File "kcauto\kcauto.py", line 174, in run_quest_logic
    qst.quest.goto()
  File "kcauto\util\core_base.py", line 32, in goto
    nav.navigate.to(self.module_name)
  File "kcauto\nav\nav.py", line 96, in to
    current_location.navigate_to(destination)
  File "kcauto\nav\nodes.py", line 212, in navigate_to
    kca_u.kca.click('top_menu_quest')
  File "kcauto\util\kca.py", line 450, in click
    self._chrome_driver_click_method(region, pad)
  File "kcauto\util\kca.py", line 562, in _chrome_driver_click_method
    x = randint(r.x - x_pad - pad[3], r.x + r.w - x_pad + pad[1])
AttributeError: 'str' object has no attribute 'x'
```

**Comment by Danielosama** [comment]
@mrmin123  Just to be sure, the "Chrome Driver" option doesn't work correctly right?
I've been trying to do a single run of 1-1 as a test, but it would just try to Refresh Home without success ad nauseam.

**Comment by mrmin123** [comment]
Yea I've heard weird reports of kcauto not playing well with Chrome Driver, such as this refresh bug. I still haven't had a chance to sit down and pin it down, so I'd suggest sticking to the Direct Control driver for now. I'll update this ticket when I have more info.
