### ISSUE TITLE
Error _tkinter.TclError: unknown option "-relief"

### ISSUE THREAD

**Issue by loadinglab3** [perryhuynh/kcauto#422]
When I try to run kcauto I go the following error message. 

`[2019-12-11 02:13:06] Initializing kcauto vv8.0.0-rc1 GUI.
[2019-12-11 02:13:06] Starting kcauto GUI.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kcauto/__main__.py", line 29, in <module>
    gui_main()
  File "kcauto/kcauto_gui.py", line 59, in gui_main
    update_gui(window, event, values)
  File "kcauto/kcauto_gui.py", line 173, in update_gui
    LayoutBase.update_widgets(window)
  File "kcauto/gui/layout_base.py", line 181, in update_widgets
    window[element].Widget.configure(relief='flat')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-relief"`

The environment is MacOS with python 3.7.3.

**Comment by loadinglab3** [comment]
CLI mode might work but I am not sure how to edit the config.json... Is there a guide about what to put in each category?

**Comment by perryhuynh** [comment]
#401 

Known issue on OSX there should be a "fix" in the issue I referenced
