### ISSUE TITLE
Resupply Issue

### ISSUE THREAD

**Issue by aleksandercs** [perryhuynh/kcauto#423]
I encountered the same problem with 3.7.5. Is there something I should do?

Traceback (most recent call last):
  File "C:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kcauto\__main__.py", line 19, in <module>
    kcauto_main()
  File "kcauto\kcauto_wrapper.py", line 32, in kcauto_main
    _.kcauto.run_resupply_logic(home_after=True)
  File "kcauto\kcauto.py", line 129, in run_resupply_logic
    if res.resupply.need_to_resupply:
  File "kcauto\resupply\resupply_core.py", line 19, in need_to_resupply
    fleets = [fleet.fleet_id for fleet in self._get_fleets_to_resupply()]
  File "kcauto\resupply\resupply_core.py", line 63, in _get_fleets_to_resupply
    if fleet.enabled and fleet.needs_resupply:
  File "kcauto\fleet\fleet.py", line 123, in needs_resupply
    if ship.needs_resupply:
  File "kcauto\ships\ship.py", line 90, in needs_resupply
    if self.fuel < self.fuel_max:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
[2019-12-12 10:30:40] Terminated kcauto subprocess via GUI.

**Comment by mrmin123** [comment]
Did you start kcauto with the game in the splash screen when you ran it the first time? It needs to be run from the splash screen to download all the necessary ship data.

**Comment by aleksandercs** [comment]
Everything works perfectly. Thank you.
