### ISSUE TITLE
Unable to proceed after init

### ISSUE THREAD

**Issue by kenahamtan** [perryhuynh/kcauto#435]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`):v8.0.0-rc1
* Operating system and/or VM:win10

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?:
consistent, unable to proceed after initializing

#### Issue

Please provide a thorough description of the issue. Screenshots, videos, or at least a step-by-step description of what is happening in the game is typically necessary to debug.

#### Log
```
[2020-02-20 06:14:57] Hooking into Chrome.
[2020-02-20 06:15:07] Connected to visual tab (8:A0599EBDBCE142A5EE5AB927C67E7FB5)
[2020-02-20 06:15:09] Connected to API tab (6:57E4C081B8B45F94A18939705B43AB28)
[2020-02-20 06:15:09] Connected to Chrome
[2020-02-20 06:15:09] Initializing kcauto vv8.0.0-rc1 in command-line mode with the 'C:/kancolle-auto/configs/exp.json' config file.
[2020-02-20 06:15:09] Loading data from 'data\temp\get_data_ship.json'.
[2020-02-20 06:15:09] Updating ship library data.
[2020-02-20 06:15:09] Finding kancolle.
[2020-02-20 06:15:09] Using UI 1 or 2
[2020-02-20 06:15:09] Game X:9, Y:324
[2020-02-20 06:15:09] Game found. Initializing regions.
[2020-02-20 06:15:09] Updating regions.
[2020-02-20 06:15:09] kcauto is initializing.
[2020-02-20 06:15:11] At home
[2020-02-20 06:15:11] Refreshing home.
[2020-02-20 06:15:13] Begin waiting for API payload(s).
[2020-02-20 06:15:14] Waiting for request 1120.82 (http://203.104.209.102/kcsapi/api_port/port)
[2020-02-20 06:15:14] Request 1120.82 received
[2020-02-20 06:15:14] Updating resource data from API.
[2020-02-20 06:15:14] Updating ship data from API.
[2020-02-20 06:15:14] Updating Repair data from API.
[2020-02-20 06:15:14] Updating fleet data from API.
[2020-02-20 06:15:14] Fleet 2 activated.
[2020-02-20 06:15:14] Fleet 2 is away on assignment.
[2020-02-20 06:15:14] Fleet 2 returns at 2020-02-20 06:34:23.
[2020-02-20 06:15:14] Fleet 3 activated.
[2020-02-20 06:15:14] Fleet 3 is away on assignment.
[2020-02-20 06:15:14] Fleet 3 returns at 2020-02-20 06:35:08.
[2020-02-20 06:15:14] Fleet 4 activated.
[2020-02-20 06:15:14] Fleet 4 is away on assignment.
[2020-02-20 06:15:14] Fleet 4 returns at 2020-02-20 08:00:19.
Traceback (most recent call last):
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "kcauto\__main__.py", line 19, in <module>
    kcauto_main()
  File "kcauto\kcauto_wrapper.py", line 32, in kcauto_main
    _.kcauto.run_resupply_logic(home_after=True)
  File "kcauto\kcauto.py", line 129, in run_resupply_logic
    if res.resupply.need_to_resupply:
  File "kcauto\resupply\resupply_core.py", line 21, in need_to_resupply
    fleets = [fleet.fleet_id for fleet in self._get_fleets_to_resupply()]
  File "kcauto\resupply\resupply_core.py", line 63, in _get_fleets_to_resupply
    if fleet.enabled and fleet.needs_resupply:
  File "kcauto\fleet\fleet.py", line 123, in needs_resupply
    if ship.needs_resupply:
  File "kcauto\ships\ship.py", line 95, in needs_resupply
    if self.fuel < self.fuel_max:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
[2020-02-20 06:15:16] Terminated kcauto subprocess via GUI.
```

#### Config
```
[insert relevant config sections here; remove section if irrelevant]
```

**Comment by perryhuynh** [comment]
Start kcauto from the splash screen to refresh ship data

**Comment by kenahamtan** [comment]
Thanks that helps
