### ISSUE TITLE
Chrome Driver and refresh home

### ISSUE THREAD

**Issue by kenahamtan** [perryhuynh/kcauto#439]
*Please make sure you are on the latest version of kcauto, and that there is not already a ticket open for your issue.*

*Please remove sections of this template you do not find relevant when creating your ticket.*

#### Environment details

* kcauto version (version on first line of `CHANGELOG.md`): v8.0.0-rc1
* Operating system and/or VM: win10

#### Issue variability
Is the issue consistent (can be reproduced consistently) or is it intermittent (only happens sometimes)?: consistent

#### Issue

When using chrome driver, unable to perform refresh home.  Timeout occurred.

#### Log
```
[2020-04-08 05:23:14] Refreshing home.
[2020-04-08 05:24:05] FindFailed stacktrace:
Traceback (most recent call last):
  File "kcauto\kcauto_wrapper.py", line 28, in kcauto_main
    _.kcauto.initialization_check()
  File "kcauto\kcauto.py", line 48, in initialization_check
    nav.navigate.to('refresh_home')
  File "kcauto\nav\nav.py", line 96, in to
    current_location.navigate_to(destination)
  File "kcauto\nav\nodes.py", line 222, in navigate_to
    NEAR_EXACT)
  File "kcauto\util\kca.py", line 402, in wait
    return r.wait(self._create_asset_path(asset), wait, similarity)
  File "C:\Users\Milamber\AppData\Local\Programs\Python\Python37\lib\site-packages\pyvisauto\__init__.py", line 191, in wait
    f"{target} not found in {self} after waiting for {wait} seconds.")
pyvisauto.FindFailed: assets\nav\home_menu_sortie.png not found in [ X:54, Y:454, W:500, H:490 ] after waiting for 20 seconds.

[2020-04-08 05:24:05] End stacktrace.
[2020-04-08 05:24:05] Attempting recovery.
[2020-04-08 05:24:05] Finding kancolle.
[2020-04-08 05:24:05] Basic Recovery successful.
[2020-04-08 05:24:06] Finding kancolle.
[2020-04-08 05:24:06] kcauto is initializing.
[2020-04-08 05:24:07] At side menu
[2020-04-08 05:24:07] Going home.
```

#### Config
```
"simple expedition config"
```

**Comment by kenahamtan** [comment]
Oh, is this similar to #397 ?
