### ISSUE TITLE
combat loop doesn't close if sortie ends on resource node

### ISSUE THREAD

**Issue by Zerosonaku** [perryhuynh/kcauto#86]
combat loop doesn't close if sortie ends on resource node, and causes  the script to crash on an expedition return screen

```
[log] CLICK on L(507,319)@S(0)[0,0 1280x800] (542 msec)
[94m[2018-02-26 11:50:11] Fleet 1 damage counts: 0 heavy / 3 moderate / 0 minor[0m
[94m[2018-02-26 11:50:20] Continuing sortie.[0m
[log] CLICK on L(286,317)@S(0)[0,0 1280x800] (528 msec)
[error] script [ C:\Users\DJJMA\Downloads\kcauto-kai-master\kcauto-kai.sikuli ] stopped with error at line --unknown--
[error] Error caused by: Traceback (most recent call last):
  File "C:\Users\DJJMA\Downloads\kcauto-kai-master\kcauto-kai.sikuli\kcauto-kai.py", line 65, in <module>
    kcauto_kai.run_combat_cycle()
  File "C:\Users\DJJMA\Downloads\kcauto-kai-master\kcauto-kai.sikuli\kcauto-kai.py", line 65, in <module>
    kcauto_kai.run_combat_cycle()
  File "C:\Users\DJJMA\Downloads\kcauto-kai-master\kcauto-kai.sikuli\main.py", line 329, in run_combat_cycle
    self._run_fast_expedition_check()
  File "C:\Users\DJJMA\Downloads\kcauto-kai-master\kcauto-kai.sikuli\main.py", line 215, in _run_fast_expedition_check
    Nav.goto(self.regions, 'home')
  File "C:\Users\DJJMA\Downloads\kcauto-kai-master\kcauto-kai.sikuli\nav.sikuli\nav.py", line 239, in goto
    if current_location.name == 'home':
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by mrmin123** [comment]
Discussed in Discord originally; issue actually stems from the script blindly clicking through until the home screen is seen if ending on a resource node. Unfortunately, if there is an expedition fleet waiting to be received, this blind clicking might receive the expedition, and the next check for the home screen fails.

Logic for clicking through post-resource node screens need to be revised.
